# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_promotion_coupon_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.promotion_coupon:indexAction
        _sylius:
            sortable: true
            criteria: { promotion: $promotionId }
            filterable: true

sylius_api_promotion_coupon_create:
    path: /
    methods: [POST]
    defaults:
        _controller: sylius.controller.promotion_coupon:createAction

sylius_api_promotion_coupon_update:
    path: /{id}
    methods: [PUT, PATCH]
    defaults:
        _controller: sylius.controller.promotion_coupon:updateAction

sylius_api_promotion_coupon_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.promotion_coupon:deleteAction

sylius_api_promotion_coupon_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.promotion_coupon:showAction
