sylius_homepage:
    pattern: /
    defaults: { _controller: sylius.controller.frontend.homepage:mainAction }

sylius_currency:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/currency.yml
    prefix: /currency

sylius_taxonomy:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/taxonomy.yml

sylius_product:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/product.yml

sylius_checkout:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/checkout.yml
    prefix: /checkout

sylius_account:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/account.yml
    prefix: /account

sylius_frontend_security:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/security.yml

sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /cart

sylius_cart_summary:
    pattern: /cart
    defaults:
        _controller: sylius.controller.cart:summaryAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:summary.html.twig

sylius_cart_save:
    pattern: /cart/save
    defaults:
        _controller: sylius.controller.cart:saveAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:summary.html.twig
