sylius_frontend_main:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/main.yml

sylius_taxonomy:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/taxonomy.yml

sylius_homepage:
    pattern: /
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: HypebeastWebBundle:Frontend/Homepage:main.html.twig
            method: createHomepagePaginator

hypebeast_frontend_security:
    resource: @HypebeastWebBundle/Resources/config/routing/frontend/security.yml
