fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        store:
            client: default
            types:
                product:
                    mappings:
                        name:
                            type: string
                            boost: 10
                            analyzer: snowball
                        brand:
                            type: string
                            index: not_analyzed
                            boost: 8
                        category:
                            type: string
                            index: not_analyzed
                            boost: 5
                        color:
                            type: string
                            index: not_analyzed
                            boost: 3
                        size:
                            type: string
                            index: not_analyzed
                            include_in_all: false
                        price:
                            type: integer
                            include_in_all: false
                        sale_price:
                            type: integer
                            include_in_all: false
                        discount:
                            type: float
                            include_in_all: false
                        published_at:
                            type: date
                            format: yyyy-MM-dd HH:mm:ss
                            include_in_all: false
                        back_in_stock_at:
                            type: date
                            format: yyyy-MM-dd HH:mm:ss
                            include_in_all: false
                    persistence:
                        driver: orm
                        model: Sylius\Bundle\CoreBundle\Model\Product
                        repository: Hypebeast\Bundle\CoreBundle\Elasticsearch\Repository\ProductRepository
                        finder: ~