payum:
    security:
        token_storage:
            Sylius\Bundle\PayumBundle\Model\PaymentSecurityToken:
                doctrine:
                    driver: orm

    contexts:
        paydollar_visa:
            paydollar_direct_client_side:
                options:
                    merchant_id: %paydollar.merchant_id%
                    payment_method: VISA
                    sandbox: %paydollar.sandbox%
                actions:
                    - sylius.payum.action.order_status
                    - sylius.payum.action.obtain_credit_card
                    - hypebeast.paydollar.action.payment_details_status
                    - hypebeast.paydollar.action.capture_order_using_credit_card
                    - hypebeast.paydollar.action.capture_onsite
                    - hypebeast.paydollar.action.notify_order
            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                Sylius\Bundle\PaymentsBundle\Model\Payment:
                    doctrine:
                        driver: orm

        paydollar_master:
            paydollar_direct_client_side:
                options:
                    merchant_id: %paydollar.merchant_id%
                    payment_method: Master
                    sandbox: %paydollar.sandbox%
                actions:
                    - sylius.payum.action.order_status
                    - sylius.payum.action.obtain_credit_card
                    - hypebeast.paydollar.action.payment_details_status
                    - hypebeast.paydollar.action.capture_order_using_credit_card
                    - hypebeast.paydollar.action.capture_onsite
                    - hypebeast.paydollar.action.notify_order
            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                Sylius\Bundle\PaymentsBundle\Model\Payment:
                    doctrine:
                        driver: orm

        paydollar_amex:
            paydollar_direct_client_side:
                options:
                    merchant_id: %paydollar.merchant_id%
                    payment_method: AMEX
                    sandbox: %paydollar.sandbox%
                actions:
                    - sylius.payum.action.order_status
                    - sylius.payum.action.obtain_credit_card
                    - hypebeast.paydollar.action.payment_details_status
                    - hypebeast.paydollar.action.capture_order_using_credit_card
                    - hypebeast.paydollar.action.capture_onsite
                    - hypebeast.paydollar.action.notify_order
            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                Sylius\Bundle\PaymentsBundle\Model\Payment:
                    doctrine:
                        driver: orm

        paydollar_alipay:
            paydollar_direct_client_side:
                options:
                    merchant_id: %paydollar.merchant_id%
                    payment_method: ALIPAY
                    sandbox: %paydollar.sandbox%
                actions:
                    - sylius.payum.action.order_status
                    - sylius.payum.action.obtain_credit_card
                    - hypebeast.paydollar.action.payment_details_status
                    - hypebeast.paydollar.action.capture_order
                    - hypebeast.paydollar.action.capture_onsite
                    - hypebeast.paydollar.action.notify_order
            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                Sylius\Bundle\PaymentsBundle\Model\Payment:
                    doctrine:
                        driver: orm

        paydollar_unionpay:
            paydollar_direct_client_side:
                options:
                    merchant_id: %paydollar.merchant_id%
                    payment_method: UPOP
                    sandbox: %paydollar.sandbox%
                actions:
                    - sylius.payum.action.order_status
                    - sylius.payum.action.obtain_credit_card
                    - hypebeast.paydollar.action.payment_details_status
                    - hypebeast.paydollar.action.capture_order
                    - hypebeast.paydollar.action.capture_onsite
                    - hypebeast.paydollar.action.notify_order
            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                Sylius\Bundle\PaymentsBundle\Model\Payment:
                    doctrine:
                        driver: orm

        paypal_express_checkout:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox:   %paypal.express_checkout.sandbox%
                actions:
                    - sylius.payum.paypal.action.capture_order_using_express_checkout
                    - sylius.payum.paypal.action.notify_order
                    - sylius.payum.action.order_status
                    - sylius.payum.action.execute_same_request_with_payment_details

            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                Sylius\Bundle\PaymentsBundle\Model\Payment:
                    doctrine:
                        driver: orm

        stripe:
            omnipay:
                type: Stripe
                options:
                    apiKey:   %stripe.secret_key%
                    testMode: %stripe.test_mode%
                actions:
                    - sylius.payum.stripe.action.capture_order_using_credit_card
                    - sylius.payum.action.obtain_credit_card
                    - sylius.payum.action.order_status
                    - sylius.payum.action.execute_same_request_with_payment_details

            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                Sylius\Bundle\PaymentsBundle\Model\Payment:
                    doctrine:
                        driver: orm

        be2bill:
            be2bill:
                api:
                    options:
                        identifier: %be2bill.identifier%
                        password:   %be2bill.password%
                        sandbox:    %be2bill.sandbox%
                actions:
                    - sylius.payum.be2bill.action.capture_order_using_credit_card
                    - sylius.payum.action.obtain_credit_card
                    - sylius.payum.action.order_status
                    - sylius.payum.action.execute_same_request_with_payment_details

            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                Sylius\Bundle\PaymentsBundle\Model\Payment:
                    doctrine:
                        driver: orm

        be2bill_onsite:
            be2bill:
                api:
                    options:
                        identifier: %be2bill.identifier%
                        password:   %be2bill.password%
                        sandbox:    %be2bill.sandbox%
                actions:
                    - sylius.payum.be2bill.action.capture_order_using_be2bill_form
                    - sylius.payum.be2bill.action.notify
                    - sylius.payum.action.order_status
                    - sylius.payum.action.execute_same_request_with_payment_details

            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                Sylius\Bundle\PaymentsBundle\Model\Payment:
                    doctrine:
                        driver: orm

        dummy:
            custom:
                actions:
                    - sylius.payum.dummy.action.capture_order
                    - sylius.payum.dummy.action.order_status

            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                Sylius\Bundle\PaymentsBundle\Model\Payment:
                    doctrine:
                        driver: orm