sylius_backend_gift_card_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.gift_card:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/GiftCard:index.html.twig
            sortable: true

sylius_backend_gift_card_show:
    pattern: /show/{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.gift_card:showAction
        _sylius:
            template: SyliusWebBundle:Backend/GiftCard:show.html.twig
