# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_homepage:
    path: /
    defaults: { _controller: sylius.controller.frontend.homepage:mainAction }

sylius_session_race1:
    pattern: /session/race1
    defaults:
        _controller: sylius.controller.frontend.homepage:sessionRace1Action

sylius_session_race2:
    pattern: /session/race2
    defaults:
        _controller: sylius.controller.frontend.homepage:sessionRace2Action

sylius_currency:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/currency.yml
    prefix: /currency

sylius_locale:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/locale.yml
    prefix: /locale

sylius_checkout:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/checkout.yml
    prefix: /checkout

sylius_account:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/account.yml
    prefix: /account

sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /cart

sylius_cart_summary:
    path: /cart
    defaults:
        _controller: sylius.controller.cart:summaryAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:summary.html.twig

sylius_cart_save:
    path: /cart/save
    defaults:
        _controller: sylius.controller.cart:saveAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:summary.html.twig
